In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('student.csv')

In [3]:
df

name  sub1  sub2  sub3
0     ajay    98    78    60
1     aman    79    95    74
2  vaibhav    69    87    98
3    harry    70    76    70
4    rahul    89    78    76

In [4]:
df.to_csv('python.csv')

In [5]:
df.to_csv('python_marks.csv',index=False)

In [6]:
df.describe()

sub1       sub2       sub3
count   5.000000   5.000000   5.000000
mean   81.000000  82.800000  75.600000
std    12.469964   8.043631  13.957077
min    69.000000  76.000000  60.000000
25%    70.000000  78.000000  70.000000
50%    79.000000  78.000000  74.000000
75%    89.000000  87.000000  76.000000
max    98.000000  95.000000  98.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   sub1    5 non-null      int64 
 2   sub2    5 non-null      int64 
 3   sub3    5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 204.0+ bytes


In [8]:
df['name']

0       ajay
1       aman
2    vaibhav
3      harry
4      rahul
Name: name, dtype: object

In [9]:
df['name'][1]

'aman'

In [10]:
df['sub2'][1]=80

<ipython-input-10-84a3252331fc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sub2'][1]=80


In [11]:
df

name  sub1  sub2  sub3
0     ajay    98    78    60
1     aman    79    80    74
2  vaibhav    69    87    98
3    harry    70    76    70
4    rahul    89    78    76

In [12]:
df.index=['student 1','student 2','student 3','student 4','student 5']

In [13]:
df

name  sub1  sub2  sub3
student 1     ajay    98    78    60
student 2     aman    79    80    74
student 3  vaibhav    69    87    98
student 4    harry    70    76    70
student 5    rahul    89    78    76

In [14]:
df.index

Index(['student 1', 'student 2', 'student 3', 'student 4', 'student 5'], dtype='object')

In [15]:
df.columns

Index(['name', 'sub1', 'sub2', 'sub3'], dtype='object')

In [16]:
df.columns[0]

'name'

In [17]:
df.columns=['Name','C Marks','CPP Marks','Python Marks']

In [18]:
df

Name  C Marks  CPP Marks  Python Marks
student 1     ajay       98         78            60
student 2     aman       79         80            74
student 3  vaibhav       69         87            98
student 4    harry       70         76            70
student 5    rahul       89         78            76

In [20]:
type(df.columns)

pandas.core.indexes.base.Index

In [19]:
df.columns[2]='C++ Marks'

TypeError: Index does not support mutable operations

In [23]:
df.sort_values('Name')

Name  C Marks  CPP Marks  Python Marks
student 1     ajay       98         78            60
student 2     aman       79         80            74
student 4    harry       70         76            70
student 5    rahul       89         78            76
student 3  vaibhav       69         87            98

In [1]:
import numpy as np
np.random.rand(300,5)

array([[0.7950436 , 0.50934183, 0.53489786, 0.53342668, 0.68125253],
       [0.41175859, 0.98774429, 0.3532074 , 0.45588825, 0.28996813],
       [0.38752722, 0.1463534 , 0.54561306, 0.52670876, 0.88056661],
       ...,
       [0.15243713, 0.59031498, 0.13461751, 0.64461334, 0.30082086],
       [0.82599999, 0.49038414, 0.9833611 , 0.86061896, 0.07171302],
       [0.66082434, 0.30884868, 0.33804354, 0.28152602, 0.13749704]])

In [9]:
np.random.rand(300,5).ndim

2

In [28]:
np.arange(101,300)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
       231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
       257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
       270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 28

In [30]:
import pandas as pd
newdf=pd.DataFrame(np.random.rand(300,5),index=np.arange(101,401))

In [31]:
newdf

0         1         2         3         4
101  0.351950  0.355529  0.007597  0.234755  0.085628
102  0.794010  0.555950  0.816122  0.695572  0.435938
103  0.734868  0.409293  0.941522  0.186320  0.406883
104  0.511979  0.210402  0.525689  0.836427  0.220316
105  0.765660  0.125691  0.352167  0.251085  0.626003
..        ...       ...       ...       ...       ...
396  0.606597  0.810338  0.639346  0.227231  0.224116
397  0.176554  0.243128  0.562881  0.440055  0.293602
398  0.616201  0.672227  0.602471  0.069580  0.849559
399  0.864504  0.520064  0.563841  0.967791  0.684374
400  0.168774  0.883689  0.412240  0.164955  0.654521

[300 rows x 5 columns]

In [30]:
type(newdf)

pandas.core.frame.DataFrame

In [36]:
newdf.describe()

0           1           2           3           4
count  300.000000  300.000000  300.000000  300.000000  300.000000
mean     0.507104    0.479814    0.511514    0.505525    0.518522
std      0.291945    0.299694    0.283764    0.297938    0.279656
min      0.001552    0.000505    0.000543    0.002392    0.009038
25%      0.250250    0.217186    0.264595    0.255888    0.284147
50%      0.516204    0.469581    0.505684    0.508978    0.528071
75%      0.761226    0.743218    0.767446    0.772073    0.763347
max      0.993507    0.998125    0.992489    0.999701    0.998078

In [37]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 101 to 400
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       300 non-null    float64
 1   1       300 non-null    float64
 2   2       300 non-null    float64
 3   3       300 non-null    float64
 4   4       300 non-null    float64
dtypes: float64(5)
memory usage: 14.1 KB


In [40]:
newdf[0][101]=np.nan

In [41]:
newdf

0         1         2         3         4
101       NaN  0.681117  0.849424  0.682933  0.753564
102  0.903239  0.461483  0.495104  0.397866  0.132378
103  0.319807  0.139667  0.343833  0.500477  0.290911
104  0.392147  0.206199  0.601542  0.348599  0.430349
105  0.208997  0.774275  0.973166  0.030500  0.778164
..        ...       ...       ...       ...       ...
396  0.154520  0.114788  0.939223  0.474323  0.407623
397  0.879706  0.482207  0.979242  0.159726  0.179226
398  0.956255  0.856811  0.933997  0.073827  0.629085
399  0.843047  0.154839  0.415597  0.916182  0.770035
400  0.142443  0.515433  0.600340  0.794086  0.059333

[300 rows x 5 columns]

In [43]:
newdf.describe()

0           1           2           3           4
count  299.000000  300.000000  300.000000  300.000000  300.000000
mean     0.508532    0.479814    0.511514    0.505525    0.518522
std      0.291383    0.299694    0.283764    0.297938    0.279656
min      0.001552    0.000505    0.000543    0.002392    0.009038
25%      0.253704    0.217186    0.264595    0.255888    0.284147
50%      0.516587    0.469581    0.505684    0.508978    0.528071
75%      0.761463    0.743218    0.767446    0.772073    0.763347
max      0.993507    0.998125    0.992489    0.999701    0.998078

In [44]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 101 to 400
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       299 non-null    float64
 1   1       300 non-null    float64
 2   2       300 non-null    float64
 3   3       300 non-null    float64
 4   4       300 non-null    float64
dtypes: float64(5)
memory usage: 22.1 KB


In [45]:
newdf[0][101]='Python'

In [46]:
newdf

0         1         2         3         4
101    Python  0.681117  0.849424  0.682933  0.753564
102  0.903239  0.461483  0.495104  0.397866  0.132378
103  0.319807  0.139667  0.343833  0.500477  0.290911
104  0.392147  0.206199  0.601542  0.348599  0.430349
105  0.208997  0.774275  0.973166  0.030500  0.778164
..        ...       ...       ...       ...       ...
396   0.15452  0.114788  0.939223  0.474323  0.407623
397  0.879706  0.482207  0.979242  0.159726  0.179226
398  0.956255  0.856811  0.933997  0.073827  0.629085
399  0.843047  0.154839  0.415597  0.916182  0.770035
400  0.142443  0.515433  0.600340  0.794086  0.059333

[300 rows x 5 columns]

In [47]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 101 to 400
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       300 non-null    object 
 1   1       300 non-null    float64
 2   2       300 non-null    float64
 3   3       300 non-null    float64
 4   4       300 non-null    float64
dtypes: float64(4), object(1)
memory usage: 20.9+ KB


In [32]:
newdf[0][101]=0.125
newdf

0         1         2         3         4
101  0.125000  0.355529  0.007597  0.234755  0.085628
102  0.794010  0.555950  0.816122  0.695572  0.435938
103  0.734868  0.409293  0.941522  0.186320  0.406883
104  0.511979  0.210402  0.525689  0.836427  0.220316
105  0.765660  0.125691  0.352167  0.251085  0.626003
..        ...       ...       ...       ...       ...
396  0.606597  0.810338  0.639346  0.227231  0.224116
397  0.176554  0.243128  0.562881  0.440055  0.293602
398  0.616201  0.672227  0.602471  0.069580  0.849559
399  0.864504  0.520064  0.563841  0.967791  0.684374
400  0.168774  0.883689  0.412240  0.164955  0.654521

[300 rows x 5 columns]

In [49]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [50]:
newdf.index

Int64Index([101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
            ...
            391, 392, 393, 394, 395, 396, 397, 398, 399, 400],
           dtype='int64', length=300)

In [51]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [53]:
newdf

0         1         2         3         4
101     0.125  0.681117  0.849424  0.682933  0.753564
102  0.903239  0.461483  0.495104  0.397866  0.132378
103  0.319807  0.139667  0.343833  0.500477  0.290911
104  0.392147  0.206199  0.601542  0.348599  0.430349
105  0.208997  0.774275  0.973166  0.030500  0.778164
..        ...       ...       ...       ...       ...
396   0.15452  0.114788  0.939223  0.474323  0.407623
397  0.879706  0.482207  0.979242  0.159726  0.179226
398  0.956255  0.856811  0.933997  0.073827  0.629085
399  0.843047  0.154839  0.415597  0.916182  0.770035
400  0.142443  0.515433  0.600340  0.794086  0.059333

[300 rows x 5 columns]

In [57]:
newdf.to_numpy()[299]

array([0.14244265777276055, 0.5154327339372756, 0.6003400598742434,
       0.7940860510647587, 0.059333362096742226], dtype=object)

In [54]:
newdf[0].to_numpy()

array([0.125, 0.9032385050648588, 0.3198070871694584, 0.39214699297698374,
       0.2089971645460431, 0.15697366604309437, 0.18034454123601118,
       0.6983721496521118, 0.1478079765523469, 0.414796745336137,
       0.4393268575270284, 0.053127366339098425, 0.1957486315144331,
       0.3058988846319365, 0.29626695691814353, 0.6724530299302554,
       0.2916687396836952, 0.6992983875663068, 0.7984107920430273,
       0.8290087367045452, 0.5534554158187359, 0.868744616375776,
       0.6136790553245461, 0.19140518132903228, 0.3053719201397139,
       0.21364489527979236, 0.6595824103633342, 0.17364913181247488,
       0.09226841166184885, 0.21262877466104813, 0.6050688596137235,
       0.9514226302102237, 0.5007358441011344, 0.7598271926677516,
       0.9434916800034143, 0.4249340612630744, 0.2020901472056008,
       0.6107700301615222, 0.7863612899795872, 0.35044870174857945,
       0.7619369053216951, 0.2720140117147424, 0.7538619995544859,
       0.13980985244740385, 0.375686796328935